### PR TITLE
Modernize the written guide (resolves #1)

### LINKED ISSUE #1: Request: Update for new AWS dashboard (both Lamba and Skills section)
Title pretty much says it all. The dashboard has changed a lot since the creation of this tutorial and this tutorial is a great way for beginners to start as you explain it in a very good way in the video. While I understand it may be too much asked to make an updated video, it would be nice to edit the readme to reflect the new dashboard.

### PR DESCRIPTION
**Pull request by favna**
- Added yarn lockfile. You nicely already said "i'm sorry i'm not using yarn" so lets rectify that in the written guide ;)

- skills.js now outputs in the format required for the new Alexa dashboard using the alexa-app skillBuilder function

- Upgraded dependency packages

- eslintified and ES6ified all the code (arrow functions most prominently as well as prefer-destructuring on the eslint side)

- couple of extra commits coz I made some mistakes here and there

- Added "to repeat VALUE" as utterance as this is a more natural speech pattern (`ask parrot to repeat 3`). It also gives people an idea on how they should be adding more utterances in future projects.

- Readme updated, obviously. I've also tried to cover some parts that you initially only addressed in the video as well as cover cross platform coding by specifying apex and aws cli installations for Linux and Windows.

---

Also concerning this line in the test:

```diff
    parrot.express({
      expressApp: app,
-      router: express.Router(),
      debug: true,
      checkCert: false
    });
    server = app.listen(3000);
  });
```

That's a deprecation prevention in alexa-app. It was logged in the console when running the test.

### CODE REVIEW

**Comment by dblock** [comment]
I merged this. Want to help me maintain this tutorial @Favna? Maybe we can add CI and what not ...

**Comment by favna** [comment]
Well I did make my first skill, which I made with this tutorial as basis go through CircleCI tests though admittedly it was mostly copypaste from my other projects.

Code for skill is on bitbucket: https://bitbucket.org/Favna/dexa/
The CircleCI history: https://circleci.com/bb/Favna/dexa/tree/master

Sure I can help. 

***
Concerning my skill:
The skill is currently still pending approval from the Amazon team until it can be added but it is a Pokedex lookup skill that, unlike many of the others, doesn't have some long / convoluted invocation and at least for the Pokemon part nigh always returns a result as I went the extra mile and added all Pokemon and all their forms to the slot as values :^)

**Comment by dblock** [comment]
https://github.com/dblock/alexa-parrot/invitations

**Comment by favna** [comment]
@dblock I contacted you through Twitter DMs to talk about the CI progess. Figured it be better than through GitHub comments.

**Comment by dblock** [comment]
What do I need to enable and where?

**Comment by dblock** [comment]
You mentioned Circle-CI, so I enabled it for this repo, https://circleci.com/gh/dblock/alexa-parrot

**Pull request merged**
