### PR TITLE
CI service guide

### PR DESCRIPTION
**Pull request by favna**
As discussed here is the PR that covers instructions and template config files for CI services. I'll just leave Travis there along with Circle so people have options and can choose themselves. 

I've also edited the header structure on the readme a bit to flow a little better. CI stuff is at the bottom.

### CODE REVIEW

**Comment by dblock** [comment]
Cool, I see why you wanted to have both - so lets keep both? I enabled travis and circle. Add badges to README?

**Comment by favna** [comment]
added the badges and currently waiting patiently for Travis' status. 

The badges will currently not show passing because they are targeting master so we can fix that by pushing some dummy commit when the PR is merged.

As for including both ye like I said, options are great imo.

**Comment by favna** [comment]
There we go. Travis and CircleCI are passing. Had a few issues in the travis config before. It's now ready for a merge, I'll leave that for you.

**Comment by dblock** [comment]
Merged, thank you!

**Pull request merged**
